"""empty message

Revision ID: 877e72759671
Revises: 
Create Date: 2018-02-09 03:35:47.126880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877e72759671'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mst_login', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('mst_login', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('mst_login', sa.Column('lng', sa.Float(), nullable=True))
    op.drop_column('mst_login', 'vc_pass_word')
    op.drop_column('mst_login', 'vc_user_type')
    op.drop_column('mst_login', 'vc_user_name')
    op.drop_column('mst_login', 'vc_user_email')
    op.drop_column('mst_login', 'nu_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mst_login', sa.Column('nu_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mst_login', sa.Column('vc_user_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('mst_login', sa.Column('vc_user_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('mst_login', sa.Column('vc_user_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('mst_login', sa.Column('vc_pass_word', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('mst_login', 'lng')
    op.drop_column('mst_login', 'lat')
    op.drop_column('mst_login', 'id')
    # ### end Alembic commands ###
